spring.datasource.url=jdbc:h2:file:./data/test-incident-simulator;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop

incidentsim.definitions.building-blocks-location=classpath:simulation/building-blocks/*.json
incidentsim.definitions.scenarios-location=classpath:simulation/scenarios/*.json
